// Code generated by protoc-gen-grain. DO NOT EDIT.
// versions:
//  protoc-gen-grain v0.7.0
//  protoc           v3.19.4
// source: smartbulb.proto

package smartbulb

import (
	fmt "fmt"
	slog "log/slog"
	time "time"

	actor "github.com/asynkron/protoactor-go/actor"
	cluster "github.com/asynkron/protoactor-go/cluster"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

var xSmartBulbFactory func() SmartBulb

// SmartBulbFactory produces a SmartBulb
func SmartBulbFactory(factory func() SmartBulb) {
	xSmartBulbFactory = factory
}

// GetSmartBulbGrainClient instantiates a new SmartBulbGrainClient with given Identity
func GetSmartBulbGrainClient(c *cluster.Cluster, id string) *SmartBulbGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &SmartBulbGrainClient{Identity: id, cluster: c}
}

// GetSmartBulbKind instantiates a new cluster.Kind for SmartBulb
func GetSmartBulbKind(opts ...actor.PropsOption) *cluster.Kind {
	props := actor.PropsFromProducer(func() actor.Actor {
		return &SmartBulbActor{
			Timeout: 60 * time.Second,
		}
	}, opts...)
	kind := cluster.NewKind("SmartBulb", props)
	return kind
}

// GetSmartBulbKind instantiates a new cluster.Kind for SmartBulb
func NewSmartBulbKind(factory func() SmartBulb, timeout time.Duration, opts ...actor.PropsOption) *cluster.Kind {
	xSmartBulbFactory = factory
	props := actor.PropsFromProducer(func() actor.Actor {
		return &SmartBulbActor{
			Timeout: timeout,
		}
	}, opts...)
	kind := cluster.NewKind("SmartBulb", props)
	return kind
}

// SmartBulb interfaces the services available to the SmartBulb
type SmartBulb interface {
	Init(ctx cluster.GrainContext)
	Terminate(ctx cluster.GrainContext)
	ReceiveDefault(ctx cluster.GrainContext)
	TurnOn(req *emptypb.Empty, ctx cluster.GrainContext) (*emptypb.Empty, error)
	TurnOff(req *emptypb.Empty, ctx cluster.GrainContext) (*emptypb.Empty, error)
	GetState(req *emptypb.Empty, ctx cluster.GrainContext) (*GetStateResponse, error)
}

// SmartBulbGrainClient holds the base data for the SmartBulbGrain
type SmartBulbGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// TurnOn requests the execution on to the cluster with CallOptions
func (g *SmartBulbGrainClient) TurnOn(r *emptypb.Empty, opts ...cluster.GrainCallOption) (*emptypb.Empty, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "SmartBulb"), slog.String("method", "TurnOn"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes}
	resp, err := g.cluster.Request(g.Identity, "SmartBulb", reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *emptypb.Empty:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

// TurnOff requests the execution on to the cluster with CallOptions
func (g *SmartBulbGrainClient) TurnOff(r *emptypb.Empty, opts ...cluster.GrainCallOption) (*emptypb.Empty, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "SmartBulb"), slog.String("method", "TurnOff"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 1, MessageData: bytes}
	resp, err := g.cluster.Request(g.Identity, "SmartBulb", reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *emptypb.Empty:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

// GetState requests the execution on to the cluster with CallOptions
func (g *SmartBulbGrainClient) GetState(r *emptypb.Empty, opts ...cluster.GrainCallOption) (*GetStateResponse, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "SmartBulb"), slog.String("method", "GetState"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 2, MessageData: bytes}
	resp, err := g.cluster.Request(g.Identity, "SmartBulb", reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *GetStateResponse:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

// SmartBulbActor represents the actor structure
type SmartBulbActor struct {
	ctx     cluster.GrainContext
	inner   SmartBulb
	Timeout time.Duration
}

// Receive ensures the lifecycle of the actor for the received message
func (a *SmartBulbActor) Receive(ctx actor.Context) {
	switch msg := ctx.Message().(type) {
	case *actor.Started: //pass
	case *cluster.ClusterInit:
		a.ctx = cluster.NewGrainContext(ctx, msg.Identity, msg.Cluster)
		a.inner = xSmartBulbFactory()
		a.inner.Init(a.ctx)

		if a.Timeout > 0 {
			ctx.SetReceiveTimeout(a.Timeout)
		}
	case *actor.ReceiveTimeout:
		ctx.Poison(ctx.Self())
	case *actor.Stopped:
		a.inner.Terminate(a.ctx)
	case actor.AutoReceiveMessage: // pass
	case actor.SystemMessage: // pass

	case *cluster.GrainRequest:
		switch msg.MethodIndex {
		case 0:
			req := &emptypb.Empty{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				ctx.Logger().Error("[Grain] TurnOn(emptypb.Empty) proto.Unmarshal failed.", slog.Any("error", err))
				resp := cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
					WithMetadata(map[string]string{
						"argument": req.String(),
					})
				ctx.Respond(resp)
				return
			}

			r0, err := a.inner.TurnOn(req, a.ctx)
			if err != nil {
				resp := cluster.FromError(err)
				ctx.Respond(resp)
				return
			}
			ctx.Respond(r0)
		case 1:
			req := &emptypb.Empty{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				ctx.Logger().Error("[Grain] TurnOff(emptypb.Empty) proto.Unmarshal failed.", slog.Any("error", err))
				resp := cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
					WithMetadata(map[string]string{
						"argument": req.String(),
					})
				ctx.Respond(resp)
				return
			}

			r0, err := a.inner.TurnOff(req, a.ctx)
			if err != nil {
				resp := cluster.FromError(err)
				ctx.Respond(resp)
				return
			}
			ctx.Respond(r0)
		case 2:
			req := &emptypb.Empty{}
			err := proto.Unmarshal(msg.MessageData, req)
			if err != nil {
				ctx.Logger().Error("[Grain] GetState(emptypb.Empty) proto.Unmarshal failed.", slog.Any("error", err))
				resp := cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
					WithMetadata(map[string]string{
						"argument": req.String(),
					})
				ctx.Respond(resp)
				return
			}

			r0, err := a.inner.GetState(req, a.ctx)
			if err != nil {
				resp := cluster.FromError(err)
				ctx.Respond(resp)
				return
			}
			ctx.Respond(r0)
		}
	default:
		a.inner.ReceiveDefault(a.ctx)
	}
}

// onError should be used in ctx.ReenterAfter
// you can just return error in reenterable method for other errors
func (a *SmartBulbActor) onError(err error) {
	resp := cluster.FromError(err)
	a.ctx.Respond(resp)
}

func respond[T proto.Message](ctx cluster.GrainContext) func(T) {
	return func(resp T) {
		ctx.Respond(resp)
	}
}
