// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: smartbulb.proto

package smartbulb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOn          bool                   `protobuf:"varint,1,opt,name=isOn,proto3" json:"isOn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_smartbulb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_smartbulb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_smartbulb_proto_rawDescGZIP(), []int{0}
}

func (x *GetStateResponse) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

var File_smartbulb_proto protoreflect.FileDescriptor

const file_smartbulb_proto_rawDesc = "" +
	"\n" +
	"\x0fsmartbulb.proto\x12\tsmartbulb\x1a\x1bgoogle/protobuf/empty.proto\"&\n" +
	"\x10GetStateResponse\x12\x12\n" +
	"\x04isOn\x18\x01 \x01(\bR\x04isOn2\xc1\x01\n" +
	"\tSmartBulb\x128\n" +
	"\x06TurnOn\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x129\n" +
	"\aTurnOff\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\bGetState\x12\x16.google.protobuf.Empty\x1a\x1b.smartbulb.GetStateResponseB\"Z proto-cluster-tutorial/smartbulbb\x06proto3"

var (
	file_smartbulb_proto_rawDescOnce sync.Once
	file_smartbulb_proto_rawDescData []byte
)

func file_smartbulb_proto_rawDescGZIP() []byte {
	file_smartbulb_proto_rawDescOnce.Do(func() {
		file_smartbulb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_smartbulb_proto_rawDesc), len(file_smartbulb_proto_rawDesc)))
	})
	return file_smartbulb_proto_rawDescData
}

var file_smartbulb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_smartbulb_proto_goTypes = []any{
	(*GetStateResponse)(nil), // 0: smartbulb.GetStateResponse
	(*emptypb.Empty)(nil),    // 1: google.protobuf.Empty
}
var file_smartbulb_proto_depIdxs = []int32{
	1, // 0: smartbulb.SmartBulb.TurnOn:input_type -> google.protobuf.Empty
	1, // 1: smartbulb.SmartBulb.TurnOff:input_type -> google.protobuf.Empty
	1, // 2: smartbulb.SmartBulb.GetState:input_type -> google.protobuf.Empty
	1, // 3: smartbulb.SmartBulb.TurnOn:output_type -> google.protobuf.Empty
	1, // 4: smartbulb.SmartBulb.TurnOff:output_type -> google.protobuf.Empty
	0, // 5: smartbulb.SmartBulb.GetState:output_type -> smartbulb.GetStateResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_smartbulb_proto_init() }
func file_smartbulb_proto_init() {
	if File_smartbulb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_smartbulb_proto_rawDesc), len(file_smartbulb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_smartbulb_proto_goTypes,
		DependencyIndexes: file_smartbulb_proto_depIdxs,
		MessageInfos:      file_smartbulb_proto_msgTypes,
	}.Build()
	File_smartbulb_proto = out.File
	file_smartbulb_proto_goTypes = nil
	file_smartbulb_proto_depIdxs = nil
}
